services:
  fittrack:
    ports: []
    environment:
      VIRTUAL_HOST: fittrack-mikel.servidorgp.somosdelprieto.com
      VIRTUAL_PORT: 3000
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true

